### ISSUE TITLE
file does not exist

### ISSUE THREAD

**Issue by shi-jyan** [dxing97/subs2cia#18]
I just downloaded this program and when I try to execute this always comes up.`C:\Users\Vinco>
C:\Users\Vinco>subs2cia condense -i '.\Claymore - 01.mkv' -tl jp
Traceback (most recent call last):
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vinco\AppData\Local\Programs\Python\Python39\Scripts\subs2cia.exe\__main__.py", line 7, in <module>
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\site-packages\subs2cia\cli.py", line 4, in main
    subs2cia.main.start()
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\site-packages\subs2cia\main.py", line 130, in start
    sources = [AVSFile(Path(file)) for file in infiles]
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\site-packages\subs2cia\main.py", line 130, in <listcomp>
    sources = [AVSFile(Path(file)) for file in infiles]
  File "c:\users\vinco\appdata\local\programs\python\python39\lib\site-packages\subs2cia\sources.py", line 18, in __init__
    raise AssertionError(f"File {filepath} does not exist")
AssertionError: File '.\Claymore does not exist`
My files are in an external hard drives and when I tried to auto complete the path using tab the directories that my files were in didnt show up. Any one know how to fix this?

**Comment by dxing97** [comment]
For windows command prompt, use double quotes instead of single quotes: 

`subs2cia condense -i “.\Claymore - 01.mkv”`
