### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'probe'

### ISSUE THREAD

**Issue by alexander-kohler** [dxing97/subs2cia#26]
```
subs2cia:INFO:subs2cia version v0.4.1
Traceback (most recent call last):
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\site-packages\subs2cia\sources.py", line 30, in probe
    self.info = ffmpeg.probe(str(self.filepath), 'ffprobe', **{'show_chapters': None})
AttributeError: module 'ffmpeg' has no attribute 'probe'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\Scripts\subs2cia.exe\__main__.py", line 7, in <module>
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\site-packages\subs2cia\cli.py", line 4, in main
    subs2cia.main.start()
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\site-packages\subs2cia\main.py", line 208, in start
    s.probe()
  File "c:\users\xelak\appdata\local\programs\python\python39\lib\site-packages\subs2cia\sources.py", line 31, in probe
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'
```

**Comment by dxing97** [comment]
Are you using the right FFmpeg package?

https://github.com/kkroening/ffmpeg-python

**Comment by alexander-kohler** [comment]
Yes I'm using ffmpeg-python 0.2.0. I've also tried removing the other ffmpeg but I'm still getting the same error

**Comment by dxing97** [comment]
Can you try reinstalling ffmpeg-python? If other packages also used ffmpeg as their module name that might have overwritten something.

**Comment by alexander-kohler** [comment]
It's working now after reinstalling both ffmpeg and subs2cia. Thank you!

**Comment by dxing97** [comment]
Great!
